name: Sync

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'doocs/leetcode'
    steps:
    - name: Sync to gitee.com
      uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
      with:
          source-repo: git@github.com:doocs/leetcode.git
          destination-repo: git@gitee.com:Doocs/leetcode.git

    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      with:
          gitee-username: yanglbme
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: doocs/leetcode
          branch: main